sudo: false
language: rust
addons:
  postgresql: 9.5
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - postgresql-9.5

rust:
  - nightly
  - beta
  - stable

before_script:
  # Import the location of pg_ctl
  - |
      export PATH=$PATH:/usr/lib/postgresql/9.5/bin
  # Activate a clean postgres database with a holmes user
  - |
      export HOLMES_PG_SOCK_DIR=`tools/pg.bash holmes`
  # Install travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# Replace cargo with travis-cargo
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - travis-cargo --only stable doc

# If we built successfully,
after_success:
  # Upload coverage data
  - travis-cargo coveralls --no-sudo --verify
  # Upload docs if we're on master and using rustc-stable
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    # Encrypted GH_TOKEN
    - secure: "awK80V+34o170L1R6veE45eoDtzzVqxG4d1FLZxleTpOw41YsFczcCNxsUJPo0u60P24z0GRpMW7bB0QfSbsnk9zYNQ/iQTywysaqeCBLl5tpH2ESw2JRB27JD88j3WfZ2duazyJKERy7O9IPdOWlCdlw1g5ATIJMs+casI7Ces="
