sudo: false
language: rust
cache: cargo
addons:
  postgresql: 9.5
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - postgresql-9.5
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - beta
  - stable

before_script:
  # Import the location of pg_ctl
  - |
      export PATH=$PATH:/usr/lib/postgresql/9.5/bin
  # Activate a clean postgres database with a holmes user
  - |
      export HOLMES_PG_SOCK_DIR=`tools/pg.bash holmes`
  # Install travis-cargo for doc upload
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
  # Install cargo-travis and rustfmt
  - |
      (cargo install cargo-travis || true) &&
      export PATH=$HOME/.cargo/bin:$PATH
  # Create the holmes storage directory
  - mkdir -p $HOME/.holmes

script:
  - cargo build
  - cargo test
  - travis-cargo --only stable doc
#  - test $TRAVIS_RUST_VERSION != "stable" || cargo fmt -- --write-mode diff

after_success:
  - travis-cargo --only stable doc-upload
  - test $TRAVIS_RUST_VERSION != "stable" || cargo coveralls

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    # Encrypted GH_TOKEN
    - secure: "awK80V+34o170L1R6veE45eoDtzzVqxG4d1FLZxleTpOw41YsFczcCNxsUJPo0u60P24z0GRpMW7bB0QfSbsnk9zYNQ/iQTywysaqeCBLl5tpH2ESw2JRB27JD88j3WfZ2duazyJKERy7O9IPdOWlCdlw1g5ATIJMs+casI7Ces="
