language: rust
addons:
  postgresql: 9.3
before_script:
  - createuser -U postgres -ld holmes
  - psql -c "ALTER USER holmes UNENCRYPTED PASSWORD 'holmes'" -U postgres
after_success:
  - sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - mkdir kcov-master/build
  - cd kcov-master/build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/out target/kcov target/debug/lib-*
