[package]

name = "holmes"
version = "0.0.1"
authors = [ "Matthew Maurer <maurer@matthewmaurer.org>" ]
license = "MIT"
description = "Holmes Inference System"
repository = "https://github.com/maurer/holmes"

[dependencies]
postgres = { features = [ "unix_socket" ] }
postgres_array = "*"
rustc-serialize = "*"
getopts = "*"

[[test]]
name = "lib"
