[package]

name = "holmes"
version = "0.0.1"
authors = [ "Matthew Maurer <maurer@matthewmaurer.org>" ]
build = "build.rs"
license = "MIT"
description = "Holmes Inference System"
repository = "https://github.com/maurer/holmes"

[[bin]]

name = "holmes"

[build-dependencies]
capnpc = "=0.2.0"

[dependencies]
capnp = "=0.2.0"
capnp-rpc = "=0.2.1"
postgres = "*"
rustc-serialize = "*"

[[test]]
name = "lib"
